version: '3'

networks:
    sola_cs: 
    
services:

  db:
    image: solovov/ot-db
    restart: always
    container_name: ot-db
    ports:
     - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SOLA_DB=${DB_NAME}
      - GEOSERVER_PORT=${GEOSERVER_PORT}
      - HOST_IP_OR_NAME=${HOST_IP_OR_NAME}
      - CS_HTTP_PORT=${CS_HTTP_PORT}
      - TZ=${TIME_ZONE}
    networks:
       sola_cs:
           aliases:
             - database
    volumes:
     - ${DB_DATA}:/var/lib/postgresql/data

  cs:
    image: solovov/ot-cs
    restart: always
    container_name: ot-cs
    ports:
      - "${CS_ADMIN_PORT}:${CS_ADMIN_PORT}"
      - "${CS_HTTP_PORT}:${CS_HTTP_PORT}"
      - "${CS_HTTPS_PORT}:${CS_HTTPS_PORT}"
    depends_on:
      - db
    environment:
      - ADMIN_PORT=${CS_ADMIN_PORT}
      - HTTPS_PORT=${CS_HTTPS_PORT}
      - HTTP_PORT=${CS_HTTP_PORT}
      - SOLA_DB=${DB_NAME}
      - TZ=${TIME_ZONE}
    command: ${DB_PASSWORD}
    networks:
       sola_cs:
         aliases:
           - server
       
  geoserver:
    image: solovov/ot-geoserver
    restart: always
    container_name: ot-gis
    ports:
      - "${GEOSERVER_PORT}:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - SOLA_DB=${DB_NAME}
      - GEOSERVER_CSRF=${GEOSERVER_CSRF_WL}
      - TZ=${TIME_ZONE}
    command: ${DB_PASSWORD}
    networks:
       sola_cs:
           aliases:
             - gis
    volumes:
     - ${GEOSERVER_DATA}:/var/local/geoserver
     
  dbadmin:
    image: solovov/ot-dbadmin
    container_name: ot-db-admin
    restart: always
    ports:
      - "${DB_ADMIN_PORT}:80"
    volumes:
      - ${DB_ADMIN_DATA}:/backups
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
      - TZ=${TIME_ZONE}
    networks:
       sola_cs: 

  cs-backups:
    image: prodrigestivill/postgres-backup-local
    container_name: ot-db-backups
    restart: always
    volumes:
      - ${DB_BACKUPS}:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=85
      - TZ=${TIME_ZONE}
    networks:
       sola_cs: